export const ADD_NOTE_ACTION = "ADD_NOTE_ACTION";

export const ADD_NOTE_ACTION_SUCCESS = "ADD_NOTE_ACTION_SUCCESS";

export const EDIT_NOTE_ACTION = "EDIT_NOTE_ACTION";

export const EDIT_NOTE_ACTION_SUCCESS = "EDIT_NOTE_ACTION_SUCCESS";

export const DELETE_NOTE_ACTION = "DELETE_NOTE_ACTION";

export const DELETE_NOTE_ACTION_SUCCESS = "DELETE_NOTE_ACTION_SUCCESS";

export const GET_SETTINGS_ACTION = "GET_SETTINGS_ACTION";

export const GET_SETTINGS_ACTION_SUCCESS = "GET_SETTINGS_ACTION_SUCCESS";

export const GET_SETTINGS_ACTION_FAIL = "GET_SETTINGS_ACTION_FAIL";
